### ISSUE TITLE
Firefox error - arrays not initialized

### ISSUE THREAD

**Issue by xmajox** [medialize/jQuery-store#7]
I was trying to set up your plugin and it's working fine everywhere except firefox. It errors out on the first serializer's init. (dies badly)

Firebug returns the following error:

```
 TypeError: encoders is undefined
      encoders.push( "json" );
           jquery.store.js (line 347)
```

Looking at the source I noticed you were not initializing the encoders and decoders arrays which made him die.

Fix: I just had to initialize it in before starting up the serializers.

``` javascript
this.encoders = this.decoders = [];
```

**Comment by rodneyrehm** [comment]
Is there a reason you're using jQuery.store rather than something better maintained like [jStorage](http://www.jstorage.info/)?

I have a sticky note on my monitor reminding me to mark this thing as deprecated. If there is a valid reason my implementation works better for you than jStorage does, I'll reconsider…

(and thanks for the PR, much appreciated!)

**Comment by xmajox** [comment]
The reason why I picked up yours instead of $.jStorage was because of your description:

"The $.store plugin (basically) is a rewrite of the $.jStorage plugin. In contrast to $.jStorage it allows the implementor to add specialized serializers and storage drivers. It can also be initialized to store data in localStorage and window.name via the same API. Additionally $.store does not cache the contents read from localStorage (which was the main reason for the rewrite)."

Since I need to have my own "serializer" (aka lens) it seemed a perfect fit. I haven't tried jStorage though so I don't know if it eases that process nowadays. Maybe your description is just old.

**Comment by rodneyrehm** [comment]
you do realize that

``` javascript
this.encoders = this.decoders = [];
```

will cause 

``` javascript
this.encoders.push("foo");
this.decoders[0] === "foo";
```

which defeats the purpose of having separate properties, no?

**Comment by xmajox** [comment]
you are absolutely right. sorry for the rushed PR. needs to be separated ofc
